name: MBC Miner Parallel

on:
  workflow_dispatch:

jobs:
  mbcminer:
    strategy:
      matrix:
        core: [1,2,3,4,5,6]
    runs-on: ubuntu-latest
    name: Mining Core ${{ matrix.core }}
    steps:
      - name: Install & Run Miner
        run: |
          sudo apt update && sudo apt install wget tar -y
          wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.27/cpuminer-opt-linux.tar.gz
          tar -xf cpuminer-opt-linux.tar.gz
          cd cpuminer-opt-linux
          chmod +x cpuminer-sse2
          ./cpuminer-sse2 -a yespowerR16 -o stratum+tcp://stratum-eu.rplant.xyz:7068 -u mbc1q4kmmc3wcnl6duv50rfmae6pvs3q4wsmvz27fdl.runner${{ matrix.core }} -p x
